name: Build, Lint and Upload to Pypi

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine ruff

      - name: Linting with Ruff
        run: |
          ruff . --recursive

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to Pypi
        run: |
          twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}